### PR TITLE
Make version caching work on Windows (fixes #63)

### LINKED ISSUE #63: fix version caching in temp file
version caching is not working on Windows

### PR DESCRIPTION
**Pull request by alexanderwilling**
Earlier, `/tmp/.phraseapp.version` was hardcoded as file path for a cache file.

This pull request
- makes version caching work on Windows (fixes #63)
- increases the TTL of the cache file from 1 hour to 24 hours
- cleans up the code
- improves testing

### CODE REVIEW

File: check_for_update.go [hunk 1]
```diff
@@ -0,0 +1,114 @@
...
+	}
+
+	return version, nil
+}
+
+func getLatestVersionFromCache() (version *semver.Version, modified time.Time, ok bool) {
+	f, err := os.Open(versionCacheFilename)
+	if err != nil {
+		ok = false
+		return
```
Comment (tobstarr) [inline check_for_update.go]: I do no like implicit returns at all (even if there are multiple return arguments) and would always prefer using explicit ones.

File: check_for_update.go [hunk 2]
```diff
@@ -0,0 +1,114 @@
...
+	}
+	defer f.Close()
+
+	stat, err := f.Stat()
+	if err != nil {
+		ok = false
+		return
```
Comment (tobstarr) [inline check_for_update.go]: see above

File: check_for_update.go [hunk 3]
```diff
@@ -0,0 +1,114 @@
...
+		if err == nil {
+			version = versionOnline
+			ioutil.WriteFile(versionCacheFilename, []byte(version.String()), 0600)
+		}
+	}
+
+	return version, nil
+}
+
+func getLatestVersionFromCache() (version *semver.Version, modified time.Time, ok bool) {
```
Comment (tobstarr) [inline check_for_update.go]: why not just use an `error` instead of `ok bool`? We can always choose to ignore errors when using that function but would not loose the actual error information.

Comment (alexanderwilling) [inline check_for_update.go]: true, I don't know why I did that to be honest. fixed in https://github.com/phrase/phraseapp-client/pull/68/commits/0788d0368989844e8c28ec57245ddd082b3d1595.

File: check_for_update.go (hunk 1 above)
Comment (alexanderwilling) [inline check_for_update.go]: fixed in https://github.com/phrase/phraseapp-client/pull/68/commits/0788d0368989844e8c28ec57245ddd082b3d1595.

File: check_for_update.go (hunk 2 above)
Comment (alexanderwilling) [inline check_for_update.go]: fixed in https://github.com/phrase/phraseapp-client/pull/68/commits/0788d0368989844e8c28ec57245ddd082b3d1595.

File: check_for_update.go [hunk 4]
```diff
@@ -57,30 +57,26 @@ func getLatestVersion() (*semver.Version, error) {
 	return version, nil
 }
 
-func getLatestVersionFromCache() (version *semver.Version, modified time.Time, ok bool) {
+func getLatestVersionFromCache() (version *semver.Version, modified time.Time, err error) {
 	f, err := os.Open(versionCacheFilename)
 	if err != nil {
-		ok = false
-		return
+		return nil, time.Now(), err
```
Comment (tobstarr) [inline check_for_update.go]: I suppose you could just return `modified` in that case

File: check_for_update.go [hunk 5]
```diff
@@ -57,30 +57,26 @@ func getLatestVersion() (*semver.Version, error) {
...
 	}
 	defer f.Close()
 
 	stat, err := f.Stat()
 	if err != nil {
-		ok = false
-		return
+		return nil, time.Now(), err
```
Comment (tobstarr) [inline check_for_update.go]: see above

File: check_for_update.go [hunk 6]
```diff
@@ -57,30 +57,26 @@ func getLatestVersion() (*semver.Version, error) {
...
 	}
 	modified = stat.ModTime()
 
 	content, err := ioutil.ReadAll(f)
 	if err != nil {
-		ok = false
-		return
+		return nil, time.Now(), err
```
Comment (tobstarr) [inline check_for_update.go]: see above

File: check_for_update.go (hunk 4 above)
Comment (alexanderwilling) [inline check_for_update.go]: fixed in https://github.com/phrase/phraseapp-client/pull/68/commits/39738d927ce2cac252ee8e3abd203446cab08fcd

File: check_for_update.go (hunk 5 above)
Comment (alexanderwilling) [inline check_for_update.go]: fixed in https://github.com/phrase/phraseapp-client/pull/68/commits/39738d927ce2cac252ee8e3abd203446cab08fcd

File: check_for_update.go (hunk 6 above)
Comment (alexanderwilling) [inline check_for_update.go]: fixed in https://github.com/phrase/phraseapp-client/pull/68/commits/39738d927ce2cac252ee8e3abd203446cab08fcd
