### PR TITLE
return error from getLatestVersion

### LINKED ISSUE #79: nil pointer dereference in update checking
From bugsnag:
```
*errors.Error runtime error: invalid memory address or nil pointer dereference 
    /go/src/github.com/phrase/phraseapp-client/check_for_update.go:42 CheckForUpdate
    main.go:31 Run
    main.go:13 main
    runtime/proc.go:183 main
    runtime/asm_amd64.s:2086 goexit
```

The problem is `getLatestVersion` dropping the error of calling `getLatestVersionFromCache` and always returning `nil` as `err`, even when `version` was `nil`, too.

### PR DESCRIPTION
**Pull request by alexanderwilling**
fixes #79

### CODE REVIEW

**Comment by sacry-dyn** [comment]
@alexanderwilling lgtm, is there a test that could cover this as well?

File: check_for_update.go [hunk 1]
```diff
@@ -50,12 +50,13 @@ func getLatestVersion() (*semver.Version, error) {
...
-			version = versionOnline
-			ioutil.WriteFile(versionCacheFilename, []byte(version.String()), 0600)
+			ioutil.WriteFile(versionCacheFilename, []byte(versionOnline.String()), 0600)
 		}
+
+		return versionOnline, err
 	}
 
-	return version, nil
+	return version, err
```
Comment (tobstarr) [inline check_for_update.go]: Is this related to https://github.com/phrase/phraseapp-client/issues/79 ?

Is it possible that we reach this point and where err is not nil? If error is is expected to always be nil we should also always return an explicit nil so that we do not pick up an old error we are not interested in (like if we decide to handle the error on writing the cache file in the future).

Comment (alexanderwilling) [inline check_for_update.go]: Well, now (after the fix) we will never reach this point if `getLatestVersionFromCache()` returns an err != nil.
It was possible before, because this return statement was used every time, even when both `getLatestVersionFromCache()` and `getLatestVersionFromURL()` failed. In that case, the hard-coded `nil` "shadowed" the error from `getLatestVersionFromURL()`.

**Comment by alexanderwilling** [comment]
@sacry-dyn: I'll add a test for this in a different branch I'm working on where I moved update checking into its own internal package.
